
name: Deploy Development

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install and build
        run: |
          npm install
          NODE_ENV=production npm run build-${{ secrets.BUILD_NAME_DEV }}

      - name: Persist build file
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
        env:
          CI: true

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Fetch build results
        uses: actions/download-artifact@v1
        with:
          name: dist
    
      - name: Deploy to S3
        uses: actions/aws/cli@master
        with:
          args: s3 cp ./dist s3://$AWS_BUCKET_NAME --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}          
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME_DEV }}