
name: Deploy Development

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install and build
        run: |
          npm install
          NODE_ENV=production npm run build-${{ secrets.BUILD_NAME_DEV }}

      - name: Persist build file
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
        env:
          CI: true

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Fetch build results
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: deploy to S3
        run: |
          go get -v github.com/bep/s3deploy
          s3deploy -source=dist/ -bucket=${{ secrets.AWS_BUCKET_NAME_DEV }} -distribution-id=${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_DEV }}

        env:
          AWS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION: 'us-east-1'
          CI: true